name: Rust CI

on:
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/rust-ci.yml
