name: Rust CI

on:
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: ./.github/workflows/rust-fmt-lint-build-test.yml

  cd:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Extract crate metadata
        id: metadata
        run: |
          PACKAGE="localtrace"
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r --arg name "localtrace" '.packages[] | select(.name == $name) | .version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Check tag
        id: tag
        run: |
          TAG="v${{ steps.metadata.outputs.version }}"
          echo "name=${TAG}" >> $GITHUB_OUTPUT
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG}$" >/dev/null 2>&1; then
            echo "Tag ${TAG} already exists, skipping push."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${TAG} does not exist, will create and push."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Push tag
        if: steps.tag.outputs.exists == 'false'
        run: |
          TAG="${{ steps.tag.outputs.name }}"
          echo "Pushing tag ${TAG}"
          git tag "${TAG}"
          git push origin "${TAG}"
      # - name: Publish
      #   if: steps.tag.outputs.exists == 'false'
      #   run: cargo publish
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
